### ISSUE TITLE
Add Courier Resolver

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-doc-type-grid-editor#11]

**Comment by leekelleher** [comment]
Awaiting feedback from https://github.com/kasperhhk/Umbraco.CourierProviders/issues/1

**Comment by rasmusfjord** [comment]
I know nothing about doing the courier resolver, im just in dire need for it, anyone who can point me in a direction for it. The place it fails for us is on media/links and such that isnt being "translated" on courier.

**Comment by leekelleher** [comment]
The repo link posted above got deleted.

Here's the new one:
https://github.com/display/Umbraco-courier-providers

I've not used it myself yet. It would be great to get community feedback on this :-)

**Comment by rasmusfjord** [comment]
Oh Lee you, once again, handsome fella! Ill take it for a spin.

**Comment by rasmusfjord** [comment]
Not working completly yet. But will test it with Rasmus i Hope :)

**Comment by leekelleher** [comment]
Closing this issue, as a Courier data-resolver is available here:
https://github.com/leekelleher/umbraco-courier-dataresolvers

> This is a fork from the DIS/PLAY repo - I've tried to make it more community friendly.
> I'm using the Courier data-resolver for DTGE on a client project; happy to say that it's working well.
