### ISSUE TITLE
Error using doctype compositions

### ISSUE THREAD

**Issue by octerl77** [leekelleher/umbraco-doc-type-grid-editor#15]
Using doctype compositions in the doctype grid editor throws the following error in the backend render view: 

Exception Details: System.InvalidOperationException: Sequence contains no matching element
Line 11:     var content = DocTypeGridEditorHelper.ConvertValueToContent(id, docType, value);
\DocTypeGridEditor\Render\DocTypeGridEditorPreviewer.cshtml    Line: 11

Umbraco 7.2.5, doctype grid editor 0.1.1

Thx,
Andreas

**Comment by leekelleher** [comment]
Thanks @octerl77 for raising this.

@mattbrailsford - I think the `Sequence contains no matching element` error is from this line:

https://github.com/leekelleher/umbraco-doc-type-grid-editor/blob/develop/Src/Our.Umbraco.DocTypeGridEditor/Helpers/DocTypeGridEditorHelper.cs#L66

But it raises the question, shouldn't the `contentType.PropertyTypes` contain the property alias? or is something funky going on with DocType compositions?

**Comment by arknu** [comment]
I think you need to check if a composition is in use and then use the ``CompositionPropertyTypes`` property instead. ``PropertyTypes`` seems to contain only the properties of the current Content Type, not those inherited via Compositions.

**Comment by arknu** [comment]
Actually, this turned out to be even simpler: Just switch over to using ``CompositionPropertyTypes`` at all times, as this will always include all properties. Created a PR here: https://github.com/leekelleher/umbraco-doc-type-grid-editor/pull/21

**Comment by leekelleher** [comment]
@arknu Thanks for the heads up! We'll take a look at PR #21. Cheers.

**Comment by BluefinDigital** [comment]
You should definitely merge this PR and release a new version based on the other great work currently sitting in the develop branch.

Nested doctypes also fail for the same reason as the code currently stands.  

Loving this little package BTW.  Gamechanger.

**Comment by leekelleher** [comment]
Closing issue, PR #21 has been merged in.
