### ISSUE TITLE
Route hijacking

### ISSUE THREAD

**Issue by sniffdk** [leekelleher/umbraco-doc-type-grid-editor#16]
I'm using the Doc Type Grid Editor (dtge) and some route hijacking in the same project.
However, it seems that whenever I use the dtge on a node in the backend and I fill in some data, whenever I load the node, the hijacked route for the current node doc type is hit for every dtge element I have in the grid.

If you want to see the issue in action, you can download a sample application here -> https://dl.dropboxusercontent.com/u/3371537/NestedContentTest.zip

Umbraco login: admin//test
Attach a debugger to the Index action on the HomeController and then load the Home node in the backend.

Is this intentional ? And if so, could you perhaps explain whats happening here ? Or if I need to go about it some other way. Any clarification would be greatly appreciated :)

Cheers
Mads

**Comment by sniffdk** [comment]
So, I was too fast, this is not related to dtge after all, sorry :)

**Comment by mattbrailsford** [comment]
Doh! Just as I had the solution up and running too :)

**Comment by sniffdk** [comment]
Sorry man :P
