### ISSUE TITLE
Display DocType icon in panel

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-doc-type-grid-editor#19]
Consider displaying the doctype's name and icon at the top of the dialog/panel.

**Comment by mattbrailsford** [comment]
What's the use case? I'd be tempted to say not to, just because the dialog is already a bit of a cramped space so really it's just taking up valuable real-estate. If there is a good reason to though, I'd be open to implementing it.

**Comment by leekelleher** [comment]
It was something that I'd implemented on Mortar, that I thought would be a nice addition on DTGE.

![capture](https://cloud.githubusercontent.com/assets/209066/11470385/18844946-9755-11e5-8073-3ac4a2ebb071.PNG)

It let's the user know which DocType they are using.

**Comment by mattbrailsford** [comment]
I guess it could make sense for if you use the doctype menu to choose a doctype first, although I tend to create individual config entries for specific doc types so for those I don't  think it's relevant.

**Comment by leekelleher** [comment]
True.

Do we know at the point of loading in the panel if multiple doctypes were available? Wondering if we can target it that way? or would that introduce an inconsistent UI? (with user's asking why it sometimes appears, othertimes it doesn't)

No rush on this, happy to let the idea/discussion stew.

**Comment by mattbrailsford** [comment]
I was just thinking the same. We could base it on "AllowedDocTypes", so if there is more than one, show the name / icon for context. If we really wanted to cover all bases, I guess you could have a prevalue config option to set "Don't show", "Only show when multiple doc type options", "Always show"?

**Comment by leekelleher** [comment]
Closing this feature request off.  If the community want it in a future release, then we can review it again.
