### ISSUE TITLE
Make DetachedPublishedContent public

### ISSUE THREAD

**Issue by jbreuer** [leekelleher/umbraco-doc-type-grid-editor#22]
Currently DetachedPublishedContent is internal. I'm trying to see if I can register DetachedPublishedContent into the PublishedContentModelFactory for the Models Builder, but currently I can't do that.

Maybe use the same class for NestedContent and the Doc Type Grid Editor?

**Comment by leekelleher** [comment]
Closing issue, cross-posted on leekelleher/umbraco-nested-content#23
We can keep the discussion in one place. Any decision in NC will reflect in DTGE.
