### ISSUE TITLE
Issue With RTE Preview When Donut Caching Is Used

### ISSUE THREAD

**Issue by leen3o** [leekelleher/umbraco-doc-type-grid-editor#23]
We've just had a really weird problem. Working on latest Umbraco v7.2.8 and the latest DocTypeGrid Editor. We setup and grid and it was all working as expected, rendering the grid fine on the site and preview is working in the grid.

Until we added an RTE to one of the DocTypes and tried to save it. It saved, but didn't preview the view in the grid. It caused a JS error which was the following:

    A potentially dangerous Request.Form value was detected from the client (value="...Content":"<p>Is the main artic...").
    
    Description: ASP.NET has detected data in the request that is potentially dangerous because it might include HTML markup or script. The data might represent an attempt to compromise the security of your application, such as a cross-site scripting attack. If this type of input is appropriate in your application, you can include code in a web page to explicitly allow it. For more information, see http://go.microsoft.com/fwlink/?LinkID=212874. 
    
    Exception Details: System.Web.HttpRequestValidationException: A potentially dangerous Request.Form value was detected from the client (value="...Content":"<p>Is the main artic...").
    
    Source Error: 
    
    An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
    
    Stack Trace: 
    
     [HttpRequestValidationException (0x80004005): A potentially dangerous Request.Form value was detected from the client (value="...Content":"<p>Is the main artic...").]
       System.Web.HttpRequest.ValidateString(String value, String collectionKey, RequestValidationSource requestCollection) +9788428
       System.Web.<>c__DisplayClass1.<ValidateHttpValueCollection>b__2(String key, String value) +22
       System.Web.HttpValueCollection.EnsureKeyValidated(String key) +9786381
       System.Web.HttpValueCollection.Get(String name) +17
       System.Collections.Specialized.NameValueCollection.get_Item(String name) +12
       DevTrends.MvcDonutCaching.KeyGenerator.GenerateKey(ControllerContext context, CacheSettings cacheSettings) in c:\Users\moonpyk\Documents\Visual Studio 2013\Projects\MvcDonutCaching\DevTrends.MvcDonutCaching\KeyGenerator.cs:91
       DevTrends.MvcDonutCaching.DonutOutputCacheAttribute.ExecuteCallback(ControllerContext context, Boolean hasErrors) in c:\Users\moonpyk\Documents\Visual Studio 2013\Projects\MvcDonutCaching\DevTrends.MvcDonutCaching\DonutOutputCacheAttribute.cs:309
       DevTrends.MvcDonutCaching.DonutOutputCacheAttribute.OnException(ExceptionContext filterContext) in c:\Users\moonpyk\Documents\Visual Studio 2013\Projects\MvcDonutCaching\DevTrends.MvcDonutCaching\DonutOutputCacheAttribute.cs:133
       System.Web.Mvc.ControllerActionInvoker.InvokeExceptionFilters(ControllerContext controllerContext, IList`1 filters, Exception exception) +109
       System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__1e(AsyncCallback asyncCallback, Object asyncState) +423
       System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
       System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +302
       System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__17(AsyncCallback asyncCallback, Object asyncState) +30
       System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
       System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +338
       System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
       System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +316
       System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +15
       System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__2(AsyncCallback asyncCallback, Object asyncState) +71
       System.Web.Mvc.Async.WrappedAsyncResult`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +129
       System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +236
       System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48
       System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +16
       System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +103
       System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

What confused me is that it's showing DonutCaching in the stack. So I removed DonutCaching completely from the project - And voila. It's all working as expected.

The only thing I can think, is that it's to do with Html.Partial() rendering the content as they have an overide for Html.Partial("name", bool) and maybe that's being used? Or clashing?

**Comment by mattbrailsford** [comment]
Hmm, that is weird. The preview control does post raw HTML to the preview partial in order for it to have the most up to date content to render, but we use the following in the render .cshtml file to bypass any security errors like this:

var value = Request.Unvalidated.Form["value"];

It would appear then that because DonutCaching is getting involved that it somehow is intercepting these requests and accessing Request.Form and so throwing an error because the request is unsafe.

My initial line of enquiry would be to maybe see if you can turn caching off for the preview control? as really this shouldn't be cached (you are fine to cache the final front end partial).

Matt

**Comment by leen3o** [comment]
This is the weird problem. We didn't have caching on at all with the grid. We only use the donut caching attribute on the MvcControllers which render the action pages. That's why I couldn't figure out what the issue was or why Donut Caching is showing in the trace. 

Which is what made me think it's something to do with the Html.Partial() overide they have.

**Comment by mattbrailsford** [comment]
I don't see what the Html.Partial should conflict, whilst previewing, the html.partial call is done inside a C# html helper extension so it shouldn't be within scope at that point. I really don't get why DonutCache is getting involved. Could really do with someone who knows more about DonutCache as I've never used it myself. Wonder if Chris Gaskle could help?

**Comment by CGaskell** [comment]
First step is to check you're definitely bumping up against the ASP.NET Request Validation module as you're posting HTML - To check temporarily disable the request validation in your web config - 

<system.web>
    <pages validateRequest="false" />
</system.web>

If thats the case then as @mattbrailsford says it could be the DonutCache attribute trying to access the Forms collection. It would do this as it will create cache keys based on unique requests (which includes request.form and request.qs etc). That said you shouldn't have the donut caching attribute on the POST action - but I dont know much about the src here.

First off switch off the request validation, if it fixes it then it may be easiest to  disable either the validation or caching for this route or dynamically disable the validation/caching if the user is signed into the back office.

**Comment by leen3o** [comment]
Hi Chris - I should have said. We did switch off request validation in the web.config but it did nothing?

**Comment by nvisage-gf** [comment]
Assuming your using MvcDonutCaching, are you using the -pre version (.3.1-beta1); we're not seeing this with that version.

**Comment by leen3o** [comment]
No I was just using the latest normal version.

**Comment by alanmac** [comment]
I had a similar issue with Donut Caching  - see here for solution in my case:
https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/71390-dtge-not-rendering-in-backoffice-rte-request-validation-problem

**Comment by BarryFogarty** [comment]
Thanks Alan for sharing that snippet #H5YR.  I had a right mare with this too, complicated by the fact that I have a member site with a default controller set in my Umbraco startup.  Long story short I needed to handle DTGE preview mode in both my custom authorization attribute AND my custom DonutMvcCache attribute, so the call to render the preview did not fail in the backoffice.

**Comment by alanmac** [comment]
No worries Barry glad it helped

**Comment by mattbrailsford** [comment]
Here is the direct link to @alanmac's gist which to me seems like a suitable solution https://gist.github.com/alanmac/f8f1c81057a1af90c66d

Closing issue down

**Comment by nvisage-gf** [comment]
above worked with additional extra check to only allow GET requests otherwise back office would still error when trying to render dtge with richtext datatype; a post happens somewhere between grid render & dtge render.

    if (filterContext.HttpContext.Request != null && filterContext.HttpContext.Request.HttpMethod != "GET")
                {
                    // don't cache if not a GET request
                    return;
                }

**Comment by geoffbeaumont** [comment]
Unfortunately, doesn't seem to always be quite this straightforward - I've got a site (ASP.Net 4.5, MVC, Umbraco 7.5, DTGE 0.4.0 and MvcDonutCaching 1.3.1-rc1), which is hitting this issue.

I've tried switching off validation in the web.config, disabling the donut caching using the above extended attribute code, even switching validation off in the controller. Donut caching is currently disabled in the web.config, so no actual caching is happening (but clearly it's still running through the caching pipeline). The only thing I can find that works is removing the donut caching attribute entirely from the controller action.

Weirdly, although validation is turned off in the web.config, the ValidateRequest flag on the controller is always on until I switch it off, so something is forcing validation on (and presumably reactivating it).

I don't think this is a DTGE problem per-se - posting this up in case it's (vaguely) helpful to someone else, or someone can point out something I haven't thought of!

**Comment by geoffbeaumont** [comment]
Okay, two things that are worth posting:

1) The validation is triggered when MvcDonutCaching inspects form inputs when building its cache key (it does this even if caching has been switched off). This isn't using the DTGE preview model, so field level validation switching isn't applied. 

I'm not sure why I couldn't get any of the above methods of disabling the validation to work - both @alanmac's and @nvisage-gf's code appeared to run too late in the process, after the form collection had already been instantiated with a validator registered. Only an explicit ValidateInputAttribute on the controller method would enable or disable the HTML validation. Trouble is, using this to disable the validation hard codes it to off in all circumstances - not an acceptable risk on the system I'm working on. I need to be able to disable the validation *only* when DTGE is previewing, and this mechanism cannot allow public users to bypass the validation.

2) So, as what I've finished up with is a custom validation attribute which extends the standard one, as follows:

https://gist.github.com/geoffbeaumont/a314caab1c96a604869fe92cf7f9f965

It's worth noting that this system has a back office / preview instance which is IP restricted (and thus it's more acceptable to relax security restrictions on that than on the pool of front end instances), and so I can enable this validation switching using a simple AppSetting and not have it operational on any publicly accessible instance. You might need different logic (e.g. check for a back office user login, client IP number) to prevent public abuse by simply appending ?dtgePreview=1 to URLs.

It also needs to be noted that workaround requires you to decorate each controller action that is decorated with DonutOutputCache with the new validation attribute, so it's a non-starter if you don't have access to the controller code.

[UmbracoDonutCacheValidateInput(true)]
[DonutOutputCache(CacheProfile = "Page")]
public override ActionResult Index(RenderModel model)
{
    ....
}

**Comment by StefanoChiodino** [comment]
Thanks, but that didn't work for me either. nothing did, in fact. Ref. https://our.umbraco.org/projects/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/71390-dtge-not-rendering-in-backoffice-rte-request-validation-problem#comment-287605
