### ISSUE TITLE
DocTypeGridEditor.cshtml - Cannot perform runtime binding on a null reference

### ISSUE THREAD

**Issue by nvisage-gf** [leekelleher/umbraco-doc-type-grid-editor#33]
Assignment to [`previewViewPath`](https://github.com/leekelleher/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml#L12) variable fails causes exception when `Model.editor.config.previewViewPath` not set - front end render/calls appear not to use variable.

PreviewViewPath is only needed in [DocTypeGridEditorPreviewer.cshtml](https://github.com/leekelleher/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditorPreviewer.cshtml#L15).

[See also](https://github.com/leekelleher/umbraco-doc-type-grid-editor/pull/31#discussion-diff-42731221) for previous mention.

**Comment by leekelleher** [comment]
@nvisage-gf Thanks for bringing this up!

I didn't notice that the `previewPath` wasn't being used - I'll chat with @mattbrailsford about it.

**Comment by mattbrailsford** [comment]
Fixed in commit cb284a7, it now no longer tries to resolve the previewpath in the front end render control
