### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-doc-type-grid-editor#34]
The community have spoken... they want a v0.2.0 release ASAP! :shipit:

**Comment by mattbrailsford** [comment]
Depends what needs to be in it? :)

We still need to do that guid > alias thing we did in NC which is what has been holding me back

**Comment by leekelleher** [comment]
@mattbrailsford We could leave the GUID > Alias switch for v0.3?
The main one is DocType compositions, which has caught a few people out.

**Comment by mattbrailsford** [comment]
ahh yea, including me :)

**Comment by mattbrailsford** [comment]
If we are happy to hold back the guid (is that a song?) stuff till later I'm happy for a 0.2 to go out the door

**Comment by leekelleher** [comment]
[![holding back the guid](http://img.youtube.com/vi/yG07WSu7Q9w/0.jpg)](http://www.youtube.com/watch?v=yG07WSu7Q9w)

**Comment by mattbrailsford** [comment]
Ahh, I was thinking this :) 

https://www.youtube.com/watch?v=mqiH0ZSkM9I

**Comment by leekelleher** [comment]
@mattbrailsford That's a better one... I don't like Mick Hucknall anyways haha
