### ISSUE TITLE
Need a way in editor config to specify a view to use

### ISSUE THREAD

**Issue by mattbrailsford** [leekelleher/umbraco-doc-type-grid-editor#35]
Currently we use convention to choose a view with the same name of a doc type alias to render in preview / front end, however it's possible that you might want to use the same doc type for 2 different views, so it would be worthwile having an ability to specific a partial to use.

**Comment by mattbrailsford** [comment]
Fixed in commit #cb284a7 View now looks for a partial with the name of the editor config alias first, then falls back to doc type alias to allow you to reuse a doc type for multiple config definitions.

It also works with surface controllers, it'll look for DocTypeAliasSurfaceController.EditorAlias action first, then fallback to DocTypeAliasSurfaceController.DocTypeAlias action`

**Comment by slombardo** [comment]
Can you explain or document how to use this new feature? I have a doc type that I want to apply a different template to (other than the default) but can't seem to accomplish this.

**Comment by slombardo** [comment]
Gah... nm, I was trying to change the grid.editors.config.js after adding the doctype to the grid.... 
This works as designed and great job!

For anyone else who runs into the same dilema:
- removed old doctype content from grid
- changed  grid.editors.config.js editor alias to point to be same as new view alias
- re-added doctype content to the grid.
