### ISSUE TITLE
Extension method for partial preview

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-doc-type-grid-editor#4]
Exploring ideas for having an extension method helper to detect the preview (within a partial):

```csharp
Request.QueryString["dtgePreview"] == "1"
```

* `@Html.IsPreview()`
* `@Request.IsPreviewRequest()`
* `@Request.IsDTGEPreview()`

Any other suggestions?

**Comment by mattbrailsford** [comment]
Another option could be to look for an alternative view? DocTypeAliasPreview.cshtml?

**Comment by leekelleher** [comment]
:+1: 

and/or add in a `previewViewPath` to the config? [ref: grid.editors.config.js](https://github.com/leekelleher/umbraco-doc-type-grid-editor/blob/develop/Src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Config/grid.editors.config.js#L10)
With a fall-back on the regular `viewPath`?

**Comment by mattbrailsford** [comment]
yup, was thinking the same

**Comment by mattbrailsford** [comment]
Guess would could just go with the previewViewPath option on it's own then we always look for DocTypeAlias.cshtml. If it's the same as normal, then it would auto fallback to standard view path anyway. Saves looking up multiple options (can still have previewViewPath fallback to viewPath if no view found there though)

**Comment by number45** [comment]
An alternate view path or some way of providing an alternative preview view would be preferable in my opinion.  It means you can switch off certain logic or output in the CMS preview without having to litter your view with conditions.

**Comment by mattbrailsford** [comment]
What should be the default preview path? /Views/Partials/DTGEPreviews/?

**Comment by mattbrailsford** [comment]
This may be going down a rabit hole here, but what about moving the views folder aswell and move them inside the Grid partials folder where the core grid editor views are stored, so we could have:

/Views/Partials/Grid/Editors/DocTypeGridEditor/Views
/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews

Wadda you think?

**Comment by leekelleher** [comment]
I think it makes sense, as "/Views/Partials/Grid/Editors/" is where the other editor partials are.

Possibly, "/Views/Partials/Grid/Editors/DocTypeGridEditor/" (without the extra "Views" sub-folder) for front-end partials and then the "Previews" sub-folder?

**Comment by mattbrailsford** [comment]
I'd be happy to go with that.

**Comment by mattbrailsford** [comment]
I've committed a preview-view-path branch if anyone wants to try it (seems to work great for me)

https://github.com/leekelleher/umbraco-doc-type-grid-editor/tree/preview-view-path

I've generate a package file in the package folder if you just want to install and test.

I think this likely has a few breaking changes, mainly the change in view path, and I also cleaned up some method overloads that didn't get used anywhere.

**Comment by mattbrailsford** [comment]
Merged as part of commit 84d389f34c57a6aacfa239b2fb793d3b1db3828d
