### ISSUE TITLE
DTGE not sortable

### ISSUE THREAD

**Issue by abriggs-eduserv** [leekelleher/umbraco-doc-type-grid-editor#40]
Hi,

I'm having issues where DTGE based grid controls aren't 'sortable'

The dragged preview becomes the controls Icon (good) but the drop placeholders does not appear (bad!)

I'm on DTGE 0.2.0 and U7.3.5

Happy to be the guinea pig/mechanical turk on this one.

**Comment by leekelleher** [comment]
@abriggs-eduserv Apologies for not getting back to you sooner on this (again #41)

Just tried this on Umbraco 7.4.2, but unable to reproduce the issue.  I suspect that recent changes to the Grid in v7.4.x have corrected the sorting.

As with #41, I haven't explicitly tested on v7.3.5, I'm not sure how relevant it would be to do so now.
