### ISSUE TITLE
"You have unsaved changes" not being displayed

### ISSUE THREAD

**Issue by abriggs-eduserv** [leekelleher/umbraco-doc-type-grid-editor#41]
Hi,

When you add a DTGE grid control (or change a property in it) Umbraco doesn't display the "You have unsaved changes" when you navigate to another node.

I'm on DTGE 0.2.0 and U7.3.5

Happy to be the guinea pig/mechanical turk on this one too.

**Comment by leekelleher** [comment]
@abriggs-eduserv Apologies for not getting back to you on this sooner.

I've tried this out with DTGE 0.2.0 and Umbraco 7.4.2, and any edits to the DTGE data/content does prompt me with the "You have unsaved changes" notification.

I haven't tried this on Umbraco 7.3.x specifically, but suspecting that it could be more an Umbraco issue than DTGE.

I'll close this off, but feel free to re-open if you think it's still an issue with DTGE.
