### ISSUE TITLE
umbracoRedirect and dtgePreview does not like each other

### ISSUE THREAD

**Issue by runegronkjaer** [leekelleher/umbraco-doc-type-grid-editor#42]
Hi Guys,

A customer of ours ran into an issue when having some dtge content on a page and then redirecting it using umbracoRedirect. The result is, that each dtge element in the grid will show the entire html of the umbracoRedirect page. That will ofcause totally break the backoffice when viewing that node :)

As I see it this is what happens:

1. dtge will request a /1000?dtgePreview=1
2. Umbraco will 302 redirect to the umbracoRedirect page
3. dtge will no longer have dtgePreview=1 in the querystring, and will have the data from an entirely different node. And will not kick in
4. The server will return the content from the umbracoRedirect page and that will be displayed.

Can we do anything to get around the problem? I can't se how to fix it in the dtge code the way things are working right now.

Cheers
Rune

**Comment by runegronkjaer** [comment]
Nice... issue number 42!
Now you have to help me ;)

**Comment by leekelleher** [comment]
@runegronkjaer Apologies for not getting back to you sooner.

I've taken a look at this today and I can reproduce the issue - it's not pretty at all. Unfortunately the redirect kicks in well before our DTGE code can access the request. Meaning we have no idea that a redirect has happened.

The DTGE code is looking for the "dtgePreview" querystring (and whether the HTTP request method is POST).

We're totally open to suggestions on how to resolve this, but for now we'll have to mark it down as a "can't fix".
