### ISSUE TITLE
Upgraded to 7.4 DTGE content no longer working

### ISSUE THREAD

**Issue by BarFoo** [leekelleher/umbraco-doc-type-grid-editor#48]
Have been trying to get the grid to work on an upgraded 7.4 that has existing content from 7.2. 

The content no longer renders anywhere including preview mode, during debugging I noticed that the `contentTypeAlias` is empty in preview mode and that the view paths are incorrect with an additional `.cshtml` appended to the end e.g. `myView.cshtml.cshtml`. 

Brand new content works fine but on an existing upgraded site the only way to get it working is to recreate the content.

**Comment by leekelleher** [comment]
@BarFoo Did you also upgrade DTGE? (If so, what was the previous version?)

The additional `.cshtml` extension is interesting, I haven't seen that issue before.

**Comment by robertjf** [comment]
I have the same issue - here's a sample of the before and after json (after I re-entered the content on the new version):

OLD:

```javascript
              "controls": [
                {
                  "value": {
                    "docType": "35d237e3-552d-4144-843d-7982f2f10db8",
                    "value": {
                      "name": "intro",
                      "bodyText": "<h3>The crew season 2</h3>\n<p>The Crew Season ...</p>"
                    },
                    "id": "1bc1d39d-e318-5e87-c67c-4b4985f9bbb4"
                  },
                  "editor": {
                    "name": "Rich Text",
                    "alias": "richText",
                    "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
                    "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
                    "icon": "icon-article",
                    "config": {
                      "allowedDocTypes": [
                        "RichText"
                      ],
                      "enablePreview": true,
                      "viewPath": "/Views/Partials/GarageGrid/"
                    }
                  }
                }
              ]
```

NEW:
```javascript
              "controls": [
                {
                  "value": {
                    "value": {
                      "name": "intro",
                      "bodyText": "<h3>The crew season 2</h3>\n<p>The Crew Season...</p>"
                    },
                    "id": "1bc1d39d-e318-5e87-c67c-4b4985f9bbb4",
                    "dtgeContentTypeAlias": null
                  },
                  "editor": {
                    "alias": "richText"
                  }
                },
                {
                  "value": {
                    "dtgeContentTypeAlias": "RichText",
                    "value": {
                      "name": "Rich Text",
                      "bodyText": "<h3>The crew season 2</h3>\n<p>The Crew Season ...</p>"
                    },
                    "id": "790e0dcd-1872-7513-c053-22596db7c583"
                  },
                  "editor": {
                    "alias": "richText"
                  },
                  "active": false
                }
              ]
```


A few observations: 
* OLD includes editor detail, NEW has just the editor alias
* OLD has an attribute of docType in the value; NEW has id attribute - both are GUIDs
* NEW has two versions of the control - one has a dtgeContentTypeAlias set to null; the other references an actual alias, but is marked as active (it's name is also different, but the actual content is correct (bodyText attribute in this case)

Versions - 
Old grid editor is 0.1 installed as a package; and for the new Umbraco I upgraded via NuGet to the latest version (0.2.1).

**Comment by robertjf** [comment]
I've just rolled back DTGE to version 0.1 which has resolved the issue; it seems upgrading directly to 0.2.1 has a breaking change.  Also of note - when I rolled back and then went to edit the content on the node that was edited (has the new content), I now see both versions of the values reflected in the NEW json in the previous comment.

**Comment by gripusa** [comment]
We have similar issue but still not sure how we can resolve, We had 0.1.1 version and during upgrade unlike robertjf , we have not upgraded the version so it remains same. Similarly we have not seen any changes in the JSON. Although we are unable to see the content on frontend or backend. Although as experienced by others, new pages are working properly.

**Comment by gripusa** [comment]
After further debugging it seems the exception is being generated at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem method. now i figure either we are having issues the SQL call being used in this method or issue #43 is causing a havoc.

**Comment by gripusa** [comment]
I thought i update our resolution and perhaps a fix to the plugin as well. What we found out that during Umbraco upgrade, umbraco had changed the GUID of many nodes (only found out after creating a database diff). Once we ran the script to update those rows with older GUID's , we were able to run the site as normal. Now for future, i would imagine, two solutions can be adopted.
1. Upgrade umbraco process avoids this scenario by keeping the existing GUIDs'
2. Plugin code (especially the helper class) is modified to rely on GUID's to find the documenttype and documents.

**Comment by gripusa** [comment]
Although the above patch able to bring the content back but we are still unable to edit the content (backoffice) in the grids, its not rendering properly inside the grid as well.

**Comment by mattbrailsford** [comment]
Lee and I spoke to Shannon yesterday and confirmed that in 7.4 the upgrade process does indeed change all the doc type guids which is what is breaking DTGE. This should only affect people on older versions of DTGE as in more recent builds we have switched to using doc type aliases (which also has it's problems, but may be slightly more manageable).

Our suggested approach is that you should roll back to 7.3 and then upgrade DTGE in that instance. You'll need to open each DTGE instance in your pages and resave the values, but this should upgrade the saved model to the new structure referencing the alias (you can confirm all of this has worked by looking in the database and making sure you see dtgeContentTypeAlias attributes with values set. With all your values saved, you should now be safe to upgrade your installs to 7.4.

**Comment by leekelleher** [comment]
Closing this ticket. Our proposed resolution is as outlined in Matt's previous reply.
