### ISSUE TITLE
Can't edit or insert item in smaller monitors (Click-"hitbox" is really small)

### ISSUE THREAD

**Issue by NathalieLarsson** [leekelleher/umbraco-doc-type-grid-editor#5]
**Umbraco version:** 7.2.2
**DTGE version:** 0.1.1
*Maybe an Umbraco grid problem*

I have my 24" monitor standing on its side (in portrait mode) and this made it impossible to edit or "Click to insert item". Later (after I started writing on this issue) I moved my Umbraco window from the 24" to the 27" and everything started working as planned. When my browser window is smaller than 1250px the "hitbox" for my item is shifted to the side and shrinked it to around 20px wide.
Small but confusing problem. :)

![image](https://cloud.githubusercontent.com/assets/475458/6799526/e424e524-d216-11e4-9b17-db8640ecb404.png)

Any how, awesome work! :+1:

**Comment by mattbrailsford** [comment]
I fear this may be a general "Grid" problem, but I can certainly have a look to see if there are any CSS tweaks we can make to improve the hit area for our editor at the very least.

**Comment by mattbrailsford** [comment]
Ok, I think I've replicated it. So you where pysically clicking the "click to insert item" label which will have been poking out of the box and where you were clicking, was technically out side of the dotted line area, is that right?

The hit area for the click event is the whole dotteed box area, so clicking anywhere within that should launch the dialog. I'll see if I can add something else to the label to get that to trigger the click aswell should you click on it outside the bounds of the box.

**Comment by NathalieLarsson** [comment]
I have clicked around in both the green and red area (including the grey text box) and only the green area is opening the dialog. 

![click-dialog](https://cloud.githubusercontent.com/assets/475458/6801394/794079a6-d227-11e4-85c5-ce23bb64665b.png)

**Comment by mattbrailsford** [comment]
What os / browser are you using?

**Comment by NathalieLarsson** [comment]
Windows 8.1, Chrome 41 and Firefox 35

But I think I found the problem, Umbraco Forms css (umbraco.forms.css) is overriding something and when I removed that file it worked perfectly. I will check if someone already posted about this on issues.umbraco.org or otherwise I will. :) Thanks anyway!

**Comment by mattbrailsford** [comment]
Cool. Nice detective work. :)

**Comment by mattbrailsford** [comment]
Closing as it seems to be a core / umbraco forms issue.
