### ISSUE TITLE
Feature Request: NuGet

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-doc-type-grid-editor#7]
Add as NuGet package

**Comment by leekelleher** [comment]
Quick note: There might be complications around post-install/PackageActions (e.g. where we add the DocTypes to the `grid.editors.config.js`)

**Comment by leekelleher** [comment]
PR #10 will sort out most of this.  We need to verify the NuGet package, (once AppVeyor is set-up), then we can close this one off.

**Comment by mattbrailsford** [comment]
What's the next steps for this? With U4-6402 reporting that the editor configs within package manifest now works, what do we need to do to get this closed off? /cc: @Jeavon

**Comment by Jeavon** [comment]
@mattbrailsford it should be a case of removing the package action and adding to the package.manifest, what I'm not totally clear on is which Umbraco version will be the minimum requirement, I think it's 7.2.3 as U4-6402 only relates to multiple grid editors in a package and doc type grid editor has only one I think...?

**Comment by leekelleher** [comment]
Closing, @Jeavon implemented in #45
