### ISSUE TITLE
AppVeyor support/integration

### ISSUE THREAD

**Issue by leekelleher** [leekelleher/umbraco-doc-type-grid-editor#8]
Add support for AppVeyor CI builds.

**Comment by Jeavon** [comment]
@leekelleher you can assign this one to me :)

**Comment by mattbrailsford** [comment]
BOOM! :) Cheers @Jeavon

**Comment by leekelleher** [comment]
@Jeavon #h5yr! :metal:

**Comment by Jeavon** [comment]
I can port the Ditto work pretty easily. Would you like the same release pattern of using lightweight tags (GitHub) on the master branch to trigger releases?

**Comment by leekelleher** [comment]
Yeah, it works well for me - sounds like a plan!

**Comment by leekelleher** [comment]
Closing this one, PR #10 merged in.
